import { InvestigationCase } from '../types';

export const DEMO_INVESTIGATION_CASES: InvestigationCase[] = [
  {
    id: 'TB-001',
    caseReference: 'I4C-2026-0941',
    investigator: 'Inspector R. Sharma (ID: LE-9842)',
    incidentType: 'Telegram Crypto Investment Fraud',
    targetInput: '0x71C7656EC7ab88b098defb751b7401b5f6d8976f',
    inputType: 'WALLET',
    chain: 'Ethereum',
    status: 'ACTIVE',
    priority: 'HIGH',
    riskLevel: 'HIGH',
    vaspDestination: 'CoinDCX India',
    nearestDirectDepositVASP: 'CoinDCX India',
    confidenceTier: 'HIGHLY_LIKELY',
    confidenceScore: 91,
    dataSource: 'DEMO',
    createdDate: '2026-09-07 14:30 IST',
    updatedDate: '2026-09-08 11:20 IST',
    maxHops: 4,
    minTransferValue: 0.1,
    notes: 'Victim defrauded of 18.5 ETH (~₹42 Lakhs) via fake high-yield investment scheme.',
    sha256Hash: '7f8a9b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b2c3d4e5f6a7b8c9d0e1f2a',
    hashTimestamp: '2026-09-08T10:15:30Z',
    nodes: [
      {
        id: 'node-target',
        label: 'Suspect Source (0x71C...976F)',
        type: 'UNHOSTED_WALLET',
        chain: 'Ethereum',
        txCount: 14,
        totalVolume: 18.5,
        riskLevel: 'HIGH',
        role: 'Suspect Primary Wallet',
        isTarget: true,
        lastActive: '2026-09-07 14:22 IST',
      },
      {
        id: 'node-hop1',
        label: 'Intermediary 1 (0x8F2...41B9)',
        type: 'WALLET',
        chain: 'Ethereum',
        txCount: 3,
        totalVolume: 18.2,
        riskLevel: 'MEDIUM',
        role: 'Peel Intermediary',
        lastActive: '2026-09-07 14:35 IST',
      },
      {
        id: 'node-hop2',
        label: 'Intermediary 2 (0x3A1...90C2)',
        type: 'WALLET',
        chain: 'Ethereum',
        txCount: 5,
        totalVolume: 17.9,
        riskLevel: 'MEDIUM',
        role: 'Pass-through Wallet',
        lastActive: '2026-09-07 14:50 IST',
      },
      {
        id: 'node-hop3',
        label: 'CoinDCX Direct Deposit (0x71c...76f)',
        type: 'EXCHANGE_DEPOSIT_WALLET',
        chain: 'Ethereum',
        txCount: 142,
        totalVolume: 890.0,
        riskLevel: 'LOW',
        role: 'Nearest Direct-Deposit Accepting VASP Wallet',
        isNearestDirectDeposit: true,
        isDestinationVASP: true,
        vaspName: 'CoinDCX India',
        lastActive: '2026-09-07 15:10 IST',
      },
      {
        id: 'node-vasp-hot',
        label: 'CoinDCX Hot Wallet Sweep Cluster',
        type: 'EXCHANGE_HOT_WALLET',
        chain: 'Ethereum',
        txCount: 14250,
        totalVolume: 89000.0,
        riskLevel: 'LOW',
        role: 'Exchange Hot Wallet Sweeper',
        vaspName: 'CoinDCX India',
        lastActive: '2026-09-08 11:00 IST',
      },
    ],
    edges: [
      {
        id: 'edge-1',
        source: 'node-target',
        target: 'node-hop1',
        amount: 18.5,
        asset: 'ETH',
        txHash: '0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
        timestamp: '2026-09-07 14:30 IST',
        typology: 'Peel-Chain Forwarding',
        isSuspicious: true,
      },
      {
        id: 'edge-2',
        source: 'node-hop1',
        target: 'node-hop2',
        amount: 18.2,
        asset: 'ETH',
        txHash: '0x2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c',
        timestamp: '2026-09-07 14:45 IST',
        typology: 'Sequential Pass-through',
        isSuspicious: false,
      },
      {
        id: 'edge-3',
        source: 'node-hop2',
        target: 'node-hop3',
        amount: 17.5,
        asset: 'ETH',
        txHash: '0x3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d',
        timestamp: '2026-09-07 15:02 IST',
        typology: 'Direct VASP Deposit Sweep',
        isSuspicious: true,
      },
      {
        id: 'edge-4',
        source: 'node-hop3',
        target: 'node-vasp-hot',
        amount: 17.5,
        asset: 'ETH',
        txHash: '0x4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e',
        timestamp: '2026-09-07 15:15 IST',
        typology: 'Internal Exchange Consolidation',
        isSuspicious: false,
      },
    ],
    hops: [
      {
        hopIndex: 1,
        fromAddress: '0x71C7656EC7ab88b098defb751b7401b5f6d8976f',
        toAddress: '0x8F24890A11c47981D90412B009141b29E37841B9',
        txHash: '0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
        amount: 18.5,
        asset: 'ETH',
        usdValue: 46250,
        timestamp: '2026-09-07 14:30 IST',
        typology: 'Initial Transfer Out',
        isVASP: false,
      },
      {
        hopIndex: 2,
        fromAddress: '0x8F24890A11c47981D90412B009141b29E37841B9',
        toAddress: '0x3A190C2894101B27A41084E01B29E3784190C289',
        txHash: '0x2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c',
        amount: 18.2,
        asset: 'ETH',
        usdValue: 45500,
        timestamp: '2026-09-07 14:45 IST',
        typology: 'Pass-through Forwarding',
        isVASP: false,
      },
      {
        hopIndex: 3,
        fromAddress: '0x3A190C2894101B27A41084E01B29E3784190C289',
        toAddress: '0x71c7656ec7ab88b098defb751b7401b5f6d8976f',
        txHash: '0x3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d',
        amount: 17.5,
        asset: 'ETH',
        usdValue: 43750,
        timestamp: '2026-09-07 15:02 IST',
        typology: 'Nearest Direct-Deposit VASP Sweep',
        isVASP: true,
        isDirectDeposit: true,
        vaspName: 'CoinDCX India',
        entityType: 'EXCHANGE_DEPOSIT_WALLET',
      },
    ],
    typologies: [
      {
        id: 'typ-1',
        code: 'PEEL_CHAIN',
        name: 'Peel-Chain Movement',
        severity: 'MODERATE',
        explanation: 'Small fee deductions taken across 3 consecutive transfers while preserving >95% primary balance.',
        affectedNodes: ['node-hop1', 'node-hop2'],
        affectedTxHashes: ['0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b'],
      },
      {
        id: 'typ-2',
        code: 'LAYERING',
        name: 'Structured Forwarding Layering',
        severity: 'HIGH',
        explanation: 'Funds routed rapidly through multiple fresh single-use intermediary wallets within 45 minutes.',
        affectedNodes: ['node-hop1', 'node-hop2', 'node-hop3'],
        affectedTxHashes: ['0x2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c'],
      },
    ],
    attribution: {
      tier: 'HIGHLY_LIKELY',
      percentage: 91,
      baseScore: 100,
      finalScore: 91,
      primaryVASP: 'CoinDCX India',
      nearestDirectDepositVASP: 'CoinDCX India',
      nearestDirectDepositAddress: '0x71c7656ec7ab88b098defb751b7401b5f6d8976f',
      isDirectDeposit: true,
      candidateVASPs: [
        {
          vaspName: 'CoinDCX India',
          depositAddress: '0x71c7656ec7ab88b098defb751b7401b5f6d8976f',
          hopDistance: 3,
          confidenceScore: 91,
          isNearestDirectDeposit: true,
          clusterRelationship: 'CoinDCX FIU-IND Regulated Deposit Cluster',
          cooperationPriority: 'DOMESTIC',
        },
      ],
      hopDistance: 3,
      pathContinuity: 'Strong Clean Path (94.5% value preserved)',
      factors: [
        {
          label: 'Nearest Direct-Deposit VASP Match (CoinDCX India)',
          impact: 10,
          type: 'POSITIVE',
          category: 'Direct Deposit Attribution',
          description: 'Identified nearest direct-deposit accepting exchange endpoint (CoinDCX India) at 3 hops.',
        },
        {
          label: '3-Hop Path Distance Penalty',
          impact: -6,
          type: 'NEGATIVE',
          category: 'Path Continuity',
          description: 'Three intermediate hops introduce minor operational path uncertainty.',
        },
        {
          label: 'Strong Path Continuity (>94%)',
          impact: 4,
          type: 'POSITIVE',
          category: 'Flow Analysis',
          description: '17.5 ETH of original 18.5 ETH successfully reached final VASP deposit.',
        },
        {
          label: 'Recent VASP Address Verification',
          impact: 3,
          type: 'POSITIVE',
          category: 'Intelligence Quality',
          description: 'CoinDCX deposit address cluster last verified on 2026-08-15.',
        },
      ],
      primaryVASPDetails: {
        name: 'CoinDCX India',
        jurisdiction: 'India (FIU-IND Registered)',
        countryCode: 'IN',
        cooperationPriority: 'DOMESTIC',
        addressCount: 14250,
        verifiedDate: '2026-08-15',
        confidenceLevel: 'AUTHORITATIVE',
        category: 'Regulated Exchange',
        knownAddressMatches: 14250,
        complianceContact: 'nodal-officer@coindcx.com',
        isDomestic: true,
        isDirectDepositAccepting: true,
      },
    },
    evidenceList: [
      {
        id: 'ev-1',
        title: 'Nearest Direct-Deposit FIU-IND Regulated Address Match',
        type: 'DIRECT_DEPOSIT_MATCH',
        source: 'Public Labelled VASP Dataset (FIU-IND)',
        address: '0x71c7656ec7ab88b098defb751b7401b5f6d8976f',
        lastVerified: '2026-08-15',
        strength: 'STRONG',
        description: 'Target destination matches confirmed direct deposit wallet of CoinDCX India.',
      },
    ],
    timeline: [],
    alerts: [
      {
        id: 'ALT-1001',
        severity: 'HIGH',
        walletAddress: '0x71C7656EC7ab88b098defb751b7401b5f6d8976f',
        chain: 'Ethereum',
        alertType: 'FRAUD_SCAM',
        evidence: 'Telegram fake high-yield investment scam reported by victim.',
        source: 'I4C Cyber Crime Cell Intelligence',
        timestamp: '2026-09-07 14:30 IST',
        confidenceScore: 92,
        recommendedReview: 'Issue Sec 91 Cr.P.C. Disclosure & Sec 102 Account Freeze Order.',
      },
    ],
    narrative: `[KNOWN FACT] Case I4C-2026-0941 analyzed wallet 0x71C7656EC7ab88b098defb751b7401b5f6d8976f on Ethereum. Funds moved through 3 hops into nearest direct-deposit accepting exchange CoinDCX India. Attribution is classified as HIGHLY LIKELY (91%).`,
  },
  {
    id: 'TB-002',
    caseReference: 'I4C-2026-1082',
    investigator: 'Officer A. Verma (ID: LE-3310)',
    incidentType: 'Healthcare Ransomware Extortion',
    targetInput: '0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be',
    inputType: 'WALLET',
    chain: 'Ethereum',
    status: 'ACTIVE',
    priority: 'URGENT',
    riskLevel: 'CRITICAL',
    vaspDestination: 'Binance',
    nearestDirectDepositVASP: 'Binance',
    confidenceTier: 'HIGHLY_LIKELY',
    confidenceScore: 87,
    dataSource: 'DEMO',
    createdDate: '2026-09-08 09:10 IST',
    updatedDate: '2026-09-08 12:45 IST',
    maxHops: 5,
    minTransferValue: 0.5,
    notes: 'Ransom payment paid by healthcare provider following data encryption threat.',
    sha256Hash: '8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b',
    hashTimestamp: '2026-09-08T09:15:00Z',
    nodes: [
      {
        id: 'node-target',
        label: 'Ransom Source (0x3F5...F0BE)',
        type: 'UNHOSTED_WALLET',
        chain: 'Ethereum',
        txCount: 8,
        totalVolume: 42.0,
        riskLevel: 'CRITICAL',
        role: 'Extortion Ransom Collection Wallet',
        isTarget: true,
        lastActive: '2026-09-08 09:00 IST',
      },
      {
        id: 'node-hop1',
        label: 'Peel Node 1 (0x5C1...19F1)',
        type: 'WALLET',
        chain: 'Ethereum',
        txCount: 4,
        totalVolume: 41.5,
        riskLevel: 'HIGH',
        role: 'Peel Wallet',
        lastActive: '2026-09-08 09:20 IST',
      },
      {
        id: 'node-vasp',
        label: 'Binance Deposit Wallet (0x3f5...0be)',
        type: 'EXCHANGE_DEPOSIT_WALLET',
        chain: 'Ethereum',
        txCount: 1892,
        totalVolume: 4500.0,
        riskLevel: 'LOW',
        role: 'Nearest Direct-Deposit Accepting VASP Wallet',
        isNearestDirectDeposit: true,
        isDestinationVASP: true,
        vaspName: 'Binance',
        lastActive: '2026-09-08 12:30 IST',
      },
    ],
    edges: [],
    hops: [
      {
        hopIndex: 1,
        fromAddress: '0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be',
        toAddress: '0x5C119F1994101B27A41084E01B29E3784190C289',
        txHash: '0x8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b',
        amount: 42.0,
        asset: 'ETH',
        usdValue: 105000,
        timestamp: '2026-09-08 09:15 IST',
        typology: 'Ransomware Payment Outflow',
        isVASP: false,
      },
      {
        hopIndex: 2,
        fromAddress: '0x5C119F1994101B27A41084E01B29E3784190C289',
        toAddress: '0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be',
        txHash: '0x0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d',
        amount: 39.8,
        asset: 'ETH',
        usdValue: 99500,
        timestamp: '2026-09-08 10:10 IST',
        typology: 'Nearest Direct-Deposit Sweep',
        isVASP: true,
        isDirectDeposit: true,
        vaspName: 'Binance',
      },
    ],
    typologies: [
      {
        id: 'typ-ransom-1',
        code: 'RANSOMWARE_OUTFLOW',
        name: 'Healthcare Ransomware Extortion Outflow',
        severity: 'CRITICAL',
        explanation: 'Extortion funds tracked directly from victim payment wallet through peel chain obfuscation into exchange deposit.',
        affectedNodes: ['node-target'],
        affectedTxHashes: ['0x8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b'],
      },
    ],
    attribution: {
      tier: 'HIGHLY_LIKELY',
      percentage: 87,
      baseScore: 100,
      finalScore: 87,
      primaryVASP: 'Binance',
      nearestDirectDepositVASP: 'Binance',
      nearestDirectDepositAddress: '0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be',
      isDirectDeposit: true,
      hopDistance: 2,
      pathContinuity: 'Strong Continuity (94.7% retained)',
      factors: [],
    },
    evidenceList: [],
    timeline: [],
    alerts: [
      {
        id: 'ALT-1002',
        severity: 'CRITICAL',
        walletAddress: '0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be',
        chain: 'Ethereum',
        alertType: 'RANSOMWARE',
        evidence: 'BlackCat Ransomware extortion payment wallet.',
        source: 'CERT-In & Law Enforcement Ransomware Feed',
        timestamp: '2026-09-08 09:10 IST',
        confidenceScore: 96,
        recommendedReview: 'Urgent Sec 102 Account Freeze Order to Binance Compliance.',
      },
    ],
    narrative: `[KNOWN FACT] Case I4C-2026-1082 analyzed ransomware wallet 0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be. Nearest direct-deposit accepting VASP identified as Binance (87% confidence).`,
  },
  {
    id: 'TB-003',
    caseReference: 'I4C-2026-1205',
    investigator: 'Inspector S. Kulkarni (ID: LE-7712)',
    incidentType: 'Darknet Market Narcotics Proceeds',
    targetInput: 'bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',
    inputType: 'WALLET',
    chain: 'Bitcoin',
    status: 'ACTIVE',
    priority: 'HIGH',
    riskLevel: 'HIGH',
    vaspDestination: 'WazirX India',
    nearestDirectDepositVASP: 'WazirX India',
    confidenceTier: 'PROBABLE',
    confidenceScore: 78,
    dataSource: 'DEMO',
    createdDate: '2026-09-06 18:00 IST',
    updatedDate: '2026-09-08 10:00 IST',
    maxHops: 6,
    minTransferValue: 0.05,
    notes: 'Multi-input UTXO aggregation across Wasabi CoinJoin mixer pool into domestic exchange.',
    nodes: [],
    edges: [],
    hops: [],
    typologies: [
      {
        id: 'typ-btc-1',
        code: 'DARKNET_PROCEEDS',
        name: 'Darknet Vendor Proceeds',
        severity: 'HIGH',
        explanation: 'Bitcoin proceeds originating from illegal online narcotics vendor address cluster.',
        affectedNodes: [],
        affectedTxHashes: [],
      },
    ],
    attribution: {
      tier: 'PROBABLE',
      percentage: 78,
      baseScore: 100,
      finalScore: 78,
      primaryVASP: 'WazirX India',
      nearestDirectDepositVASP: 'WazirX India',
      isDirectDeposit: true,
      hopDistance: 2,
      pathContinuity: 'Moderate Path Continuity (94.8%)',
      factors: [],
    },
    evidenceList: [],
    timeline: [],
    alerts: [
      {
        id: 'ALT-1003',
        severity: 'HIGH',
        walletAddress: 'bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',
        chain: 'Bitcoin',
        alertType: 'DARKNET_MARKET',
        evidence: 'Darknet illicit vendor deposit pattern.',
        source: 'NCB / Narcotics Control Intelligence',
        timestamp: '2026-09-06 18:00 IST',
        confidenceScore: 88,
        recommendedReview: 'Issue Sec 91 Cr.P.C. Disclosure Notice to WazirX India.',
      },
    ],
    narrative: `[KNOWN FACT] Case I4C-2026-1205 analyzed Darknet proceeds wallet bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh on Bitcoin network. Nearest direct-deposit accepting VASP identified as WazirX India (78%).`,
  },
  {
    id: 'TB-004',
    caseReference: 'I4C-2026-1601',
    investigator: 'Officer R. Sharma (ID: LE-9842)',
    incidentType: 'Terrorism-Financing Risk Indicator',
    targetInput: 'T9yD1428fk820fk820fk820fk820fk820fk8',
    inputType: 'WALLET',
    chain: 'Tron',
    status: 'ACTIVE',
    priority: 'URGENT',
    riskLevel: 'CRITICAL',
    vaspDestination: 'Binance (Tron USDT Cluster)',
    nearestDirectDepositVASP: 'Binance',
    confidenceTier: 'HIGHLY_LIKELY',
    confidenceScore: 84,
    dataSource: 'DEMO',
    createdDate: '2026-09-08 07:00 IST',
    updatedDate: '2026-09-08 13:00 IST',
    maxHops: 3,
    minTransferValue: 1000,
    notes: 'High-frequency TRC-20 USDT transfers linked to suspected offshore illicit funding cluster.',
    nodes: [],
    edges: [],
    hops: [],
    typologies: [
      {
        id: 'typ-tf-1',
        code: 'TERRORISM_FINANCING_RISK',
        name: 'Terrorism-Financing Risk Indicator',
        severity: 'CRITICAL',
        explanation: 'TRC-20 USDT wallet cluster matching high-risk international intelligence watchlists.',
        affectedNodes: [],
        affectedTxHashes: [],
      },
    ],
    attribution: {
      tier: 'HIGHLY_LIKELY',
      percentage: 84,
      baseScore: 100,
      finalScore: 84,
      primaryVASP: 'Binance',
      nearestDirectDepositVASP: 'Binance',
      isDirectDeposit: true,
      hopDistance: 2,
      pathContinuity: 'High Continuity TRC-20 USDT Flow',
      factors: [],
    },
    evidenceList: [],
    timeline: [],
    alerts: [
      {
        id: 'ALT-1004',
        severity: 'CRITICAL',
        walletAddress: 'T9yD1428fk820fk820fk820fk820fk820fk8',
        chain: 'Tron',
        alertType: 'TERRORISM_FINANCING',
        evidence: 'TRC-20 USDT cluster flagged on international intelligence watchlist.',
        source: 'FIU-IND National Watchlist Feed',
        timestamp: '2026-09-08 07:00 IST',
        confidenceScore: 94,
        recommendedReview: 'Urgent Sec 102 Account Freeze Request & Financial Intelligence Report.',
      },
    ],
    narrative: `[KNOWN FACT] Case I4C-2026-1601 tracked Tron TRC-20 USDT address T9yD1428fk820fk820fk820fk820fk820fk8. Nearest direct-deposit accepting VASP identified as Binance (84%).`,
  },
  {
    id: 'TB-005',
    caseReference: 'I4C-2026-1450',
    investigator: 'Inspector P. Nambiar (ID: LE-4109)',
    incidentType: 'Cross-Bridge Defi Exploit',
    targetInput: '0x0d0707963952f2a77298587ab17fa5b169528d9c',
    inputType: 'WALLET',
    chain: 'Ethereum',
    status: 'ACTIVE',
    priority: 'HIGH',
    riskLevel: 'HIGH',
    vaspDestination: 'FixedFloat Instant Swap',
    nearestDirectDepositVASP: 'FixedFloat Instant Swap',
    confidenceTier: 'PROBABLE',
    confidenceScore: 64,
    dataSource: 'DEMO',
    createdDate: '2026-09-05 11:30 IST',
    updatedDate: '2026-09-08 08:15 IST',
    maxHops: 5,
    minTransferValue: 1.0,
    notes: 'Attacker bridged funds across Synapse Bridge to Polygon before swapping on instant non-KYC service.',
    nodes: [],
    edges: [],
    hops: [],
    typologies: [
      {
        id: 'typ-br-1',
        code: 'CHAIN_HOPPING',
        name: 'Cross-Chain Bridge Transition',
        severity: 'HIGH',
        explanation: 'Funds transferred through liquidity bridge contract into non-custodial destination chain.',
        affectedNodes: [],
        affectedTxHashes: [],
      },
    ],
    attribution: {
      tier: 'PROBABLE',
      percentage: 64,
      baseScore: 100,
      finalScore: 64,
      primaryVASP: 'FixedFloat Instant Swap',
      nearestDirectDepositVASP: 'FixedFloat Instant Swap',
      isDirectDeposit: true,
      hopDistance: 2,
      pathContinuity: 'Cross-Chain Fragmented',
      factors: [],
    },
    evidenceList: [],
    timeline: [],
    narrative: `[KNOWN FACT] Case I4C-2026-1450 analyzed wallet 0x0d0707963952f2a77298587ab17fa5b169528d9c across cross-chain bridge transitions. Nearest direct-deposit service identified as FixedFloat Instant Swap (64%).`,
  },
  {
    id: 'TB-006',
    caseReference: 'I4C-2026-1890',
    investigator: 'Officer M. Roy (ID: LE-6102)',
    incidentType: 'Sanctioned Privacy Mixer Wash',
    targetInput: '0x12d66f87a04a9e220743712ce6d9bb1b5616b8fc',
    inputType: 'WALLET',
    chain: 'Ethereum',
    status: 'NEEDS_REVIEW',
    priority: 'URGENT',
    riskLevel: 'CRITICAL',
    vaspDestination: 'Tornado Cash Protocol (Mixer)',
    nearestDirectDepositVASP: 'No Direct Deposit VASP (Mixer Interaction)',
    confidenceTier: 'INSUFFICIENT_DATA',
    confidenceScore: 24,
    dataSource: 'DEMO',
    createdDate: '2026-09-08 02:00 IST',
    updatedDate: '2026-09-08 14:00 IST',
    maxHops: 3,
    minTransferValue: 10.0,
    notes: 'Suspect deposited 100 ETH directly into Tornado Cash smart contract pool.',
    nodes: [],
    edges: [],
    hops: [],
    typologies: [
      {
        id: 'typ-mix-1',
        code: 'MIXER_INTERACTION',
        name: 'Sanctioned Privacy Mixer Interaction',
        severity: 'CRITICAL',
        explanation: 'Direct deposit into zero-knowledge privacy pool (Tornado Cash 100 ETH contract). Cryptographic link severed.',
        affectedNodes: [],
        affectedTxHashes: [],
      },
    ],
    attribution: {
      tier: 'INSUFFICIENT_DATA',
      percentage: 24,
      baseScore: 100,
      finalScore: 24,
      primaryVASP: 'Tornado Cash Protocol (Mixer)',
      nearestDirectDepositVASP: 'No Direct Deposit VASP (Severed by Mixer)',
      isDirectDeposit: false,
      hopDistance: 1,
      pathContinuity: 'Severed by Zero-Knowledge Privacy Pool',
      factors: [],
    },
    evidenceList: [],
    timeline: [],
    alerts: [
      {
        id: 'ALT-1006',
        severity: 'CRITICAL',
        walletAddress: '0x12d66f87a04a9e220743712ce6d9bb1b5616b8fc',
        chain: 'Ethereum',
        alertType: 'SANCTIONED_MIXER',
        evidence: 'OFAC Sanctioned Smart Contract Deposit (Tornado Cash 100 ETH pool).',
        source: 'OFAC Sanctions & Smart Contract Registry',
        timestamp: '2026-09-08 02:00 IST',
        confidenceScore: 100,
        recommendedReview: 'Flag interaction for enhanced forensic analysis.',
      },
    ],
    narrative: `[KNOWN FACT] Target wallet 0x12d66f87a04a9e220743712ce6d9bb1b5616b8fc deposited 100 ETH directly into Tornado Cash smart contract. Cryptographic anonymity pool severs deterministic transaction path.`,
  }
];
