import { InvestigationCase } from '../../types';

export function generateLegalNoticeDraft(caseData: Partial<InvestigationCase>): string {
  const caseRef = caseData.caseReference || 'TB-2026-0941';
  const investigator = caseData.investigator || 'Inspector R. Sharma, Cyber Crime Cell';
  const vaspName = caseData.nearestDirectDepositVASP || caseData.vaspDestination || 'CoinDCX India / Binance';
  const targetWallet = caseData.targetInput || '0x71C7656EC7ab88b098defb751b7401b5f6d8976f';
  const chain = caseData.chain || 'Ethereum';
  const dateStr = new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });

  return `FORMAL DISCLOSURE REQUEST UNDER SECTION 91 Cr.P.C. / BNSS 2023
(OFFICIAL LEGAL NOTICE DRAFT - REQUIRES AUTHORIZED OFFICER REVIEW & SUBMISSION)

TO:
The Nodal Officer / Compliance Officer
${vaspName}
Legal & Regulatory Response Division

DATE: ${dateStr}
REFERENCE CASE NO: ${caseRef}
INVESTIGATING OFFICER: ${investigator}
AGENCY: Cyber Crime Investigation Division

SUBJECT: Urgent Request for KYC Details, Transaction Logs, and Account Logs under Ongoing Investigation

1. PREAMBLE & AUTHORITY:
   This notice is issued in connection with an active criminal investigation into cryptocurrency fraud / cybercrime tracked under reference ${caseRef}. Pursuant to public blockchain intelligence analysis conducted via CHAIN-INTEL, funds originating from suspect address ${targetWallet} (${chain}) have been traced hop-by-hop to nearest direct-deposit accepting exchange infrastructure controlled by your exchange (${vaspName}).

2. TARGET SPECIFICATION:
   • Blockchain: ${chain}
   • Target Source Wallet: ${targetWallet}
   • Nearest Direct-Deposit VASP Address: ${caseData.attribution?.nearestDirectDepositAddress || caseData.hops?.[caseData.hops.length - 1]?.toAddress || 'Identified VASP Deposit Account'}
   • Evidence Confidence Level: ${caseData.confidenceTier || 'HIGHLY LIKELY'} (${caseData.confidenceScore || 91}%)
   • Report SHA-256 Hash: ${caseData.sha256Hash || '7f8a9b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b2c3d4e5f6a7b8c9d0e1f2a'}

3. REQUIRED DISCLOSURES WITHIN 24 HOURS:
   A. Complete Subscriber Identity Details (KYC / AML files, Name, PAN/Aadhaar, Passport, Verified Email, Phone Number, Registered IP Logs).
   B. Full Account Ledger and Fiat Bank Withdrawal / Transfer Logs associated with the deposit address.

4. CERTIFICATION & DISCLAIMER:
   This document is an automated draft generated by CHAIN-INTEL Forensic Workstation for authorized law enforcement personnel. Final legal service requires signature and seal by the designated Investigating Officer.

ISSUED BY:
${investigator}
Cyber Crime Division Workstation ID: LE-WORKSTATION-09
Contact Email: compliance-requests@cybercrime.gov.in`;
}

export function generateFreezeRequestDraft(caseData: Partial<InvestigationCase>): string {
  const caseRef = caseData.caseReference || 'TB-2026-0941';
  const investigator = caseData.investigator || 'Inspector R. Sharma, Cyber Crime Cell';
  const vaspName = caseData.nearestDirectDepositVASP || caseData.vaspDestination || 'CoinDCX India';
  const targetWallet = caseData.targetInput || '0x71C7656EC7ab88b098defb751b7401b5f6d8976f';
  const chain = caseData.chain || 'Ethereum';
  const dateStr = new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });

  return `ORDER FOR RESTRAINT / FREEZING OF CRYPTOCURRENCY ASSETS UNDER SECTION 102 Cr.P.C. / BNSS 2023
(OFFICIAL LEGAL FREEZE REQUEST DRAFT - REQUIRES AUTHORIZED OFFICER REVIEW & SUBMISSION)

TO:
The Nodal Officer / Compliance Officer
${vaspName}
Legal Response & Risk Division

DATE: ${dateStr}
REFERENCE CASE NO: ${caseRef}
INVESTIGATING OFFICER: ${investigator}
AGENCY: Cyber Crime Investigation Division

SUBJECT: URGENT ORDER TO FREEZE SUSPECT ACCOUNT & PREVENT DIVERSION OF PROCEEDS OF CRIME

1. STATUTORY POWER & ORDER:
   In exercise of powers conferred under Section 102 of the Code of Criminal Procedure, 1973 (and corresponding provisions under BNSS 2023), you are hereby directed to IMMEDIATELY RESTRAIN AND FREEZE all crypto assets, fiat balances, and pending withdrawal requests linked to the target deposit address identified below.

2. TARGET DEPOSIT SPECIFICATIONS:
   • Suspect Origin Address: ${targetWallet} (${chain})
   • Attributed Nearest Direct-Deposit VASP: ${vaspName}
   • Target VASP Deposit Address: ${caseData.attribution?.nearestDirectDepositAddress || 'Identified Exchange Deposit Wallet'}
   • Traced Crime Proceeds: ${caseData.hops?.[caseData.hops.length - 1]?.amount || 17.5} ${chain === 'Bitcoin' ? 'BTC' : 'ETH'}
   • Attribution Evidence Score: ${caseData.confidenceScore || 91}% (${caseData.confidenceTier || 'HIGHLY_LIKELY'})
   • Cryptographic Report Hash: ${caseData.sha256Hash || '7f8a9b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b2c3d4e5f6a7b8c9d0e1f2a'}

3. REQUIRED IMMEDIATE COMPLIANCE ACTIONS:
   A. Place an immediate administrative freeze on the account receiving deposits from the specified address.
   B. Prevent any fiat bank transfer, P2P sale, or crypto withdrawal from the subject account.
   C. Transmit confirmation of account restraint to compliance-requests@cybercrime.gov.in within 4 hours.

4. AUTHORIZATION DISCLAIMER:
   DRAFT GENERATED BY CHAIN-INTEL WORKSTATION — REQUIRES AUTHORIZED OFFICER SIGNATURE & LEGAL SEAL BEFORE SUBMISSION.

ISSUED BY:
${investigator}
Cyber Crime Division Workstation ID: LE-WORKSTATION-09`;
}
